Replace expires cookie attribute with max-age attribute
maxcountryman/flask-login pull request #823
Opened 2023-11-10 18:58 UTC by tvuotila

Internet Explorer doesn't support max-age cookie attribute. I don't know any other reason to use expires instead of max-age.

Max-age works even if client or server clocks have wrong time.

2023-11-22 13:22 UTC, sebastiaguevara commented
me pueden ayudar 
La FIFA quiere que le ayudes a crear una aplicación web que contenga la información de los equipos que van 
a ir al próximo mundial de la FIFA México/Estados Unidos/Canadá 2026, así que te dicen que debes crear los 
modelos y CRUD’s teniendo en cuenta la siguiente información:
Historias de usuario:
- Login
- Logout
- Registro de usuario
- Página principal
Equipo
- Nombre del Equipo
- Imagen de Bandera
- Escudo del Equipo
Jugador
- Nombre
- Apellido
- Foto del jugador
- Fecha de nacimiento
- Posición en la que juega
- Número de camiseta
- ¿Es titular?
- Equipo
Posición de juego
- Nombre
- Descripción
Técnico
- Nombre
- Apellido
- Fecha de nacimiento
- Nacionalidad [tabla, choices]
- Rol (técnico | asistente | médico | preparador

2024-01-21 13:01 UTC, maxcountryman commented
Why not use both? That's what Django seems to do.

2024-01-22 07:15 UTC, tvuotila commented
> Why not use both? That's what Django seems to do.

I checked [the `max-age` support](https://caniuse.com/mdn-http_headers_set-cookie_max-age) again. Seems like I was wrong and everything supports max-age. 

Not using both has these benefits:
 - Simpler code
 - Doesn't reveal server time skew
 - (Smaller response size)

2024-01-22 09:40 UTC, tvuotila commented
> Why not use both? That's what Django seems to do.

I investigated this more and Flask also uses both: 
 - `LoginManager._set_cookie` calls `Response.set_cookie`
 - `Response.set_cookie` calls `werkzeug.http.dump_cookie`
 - The `dump_cookie` has default argument `sync_expires: automatically set expires if max_age is defined but expires not.`

Thus, in the end, this PR sets both, `expires` and `max-age`. At least, until `werkzeug` changes the defaults.

2024-01-22 13:03 UTC, maxcountryman requested changes

2024-01-22 13:03 UTC, maxcountryman commented on CHANGES.md
> +- Replace `expires` attribute with `max-age` in "remember_me" cookie. #823
This should read as additive since it's no longer replacing.

2024-01-22 13:03 UTC, maxcountryman commented on tests/test_login.py
> -        self.assertIsNotNone(cookie.expires)
This shouldn't be removed. Likewise below.

2024-01-22 13:03 UTC, maxcountryman commented on tests/test_login.py
> -    def test_set_cookie_with_invalid_duration_raises_exception(self):
Why is this being removed?

2024-01-22 13:03 UTC, maxcountryman commented on tests/test_login.py
> -        with patch("flask_login.login_manager.datetime") as mock_dt:
Likewise here.

2024-04-01 17:35 UTC, closed without merging